services:
  nginx:
    image: nginx:alpine
    container_name: llm_proxy_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      # Uncomment the line below when you have SSL certificates
      # - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - llm_proxy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  llm_proxy:
    driver: bridge